# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Evento' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Events
pod 'Alamofire'
pod 'AlamofireImage'
pod 'Firebase/Core'
pod 'Firebase/Messaging'

  target 'EventoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
